In [1]:
import pandas as pd

In [3]:
file_url = 'https://media.githubusercontent.com/media/musthave-ML10/data_source/main/sample.csv';
sample = pd.read_csv(file_url)
sample

Var_1  Var_2
0       1      2
1       3      4
2       2      5
3       5      6
4       3      2
5       1      1
6       2      6
7       5      7
8       6      8
9       7      4
10      7      7
11      8      3
12      9      7
13      3      9
14      2      2
15      1      3
16      2      6
17      2      4
18      3      3

In [5]:
sample_dic = pd.DataFrame({'name':['John', 'Ann', 'Kevin'], 'age': [23, 22, 21]})
sample_dic

name  age
0   John   23
1    Ann   22
2  Kevin   21

In [7]:
sample_dic = pd.DataFrame([
    [1, 2], 
    [3, 4], 
    [5, 6], 
    [7, 8]],
    columns = ['var_1', 'var_2'], 
    index = ['a', 'b', 'c', 'd']
)
sample_dic

var_1  var_2
a      1      2
b      3      4
c      5      6
d      7      8

In [36]:
file_url = 'https://media.githubusercontent.com/media/musthave-ML10/data_source/main/sample_df.csv';
sample_df = pd.read_csv(file_url, index_col = 0) # 첫번째 열을 인덱스로 지정 
sample_df

var_1  var_2  var_3  var_4  var_5
a      2      2      1      4      3
b      4      3      3      7      1
c      5      4      6      3      5
d      1      4      5      6      7
e      4      5      7      8      3
f      5      4      8      9      4
g      7      5      2      0      6
h      8      8      1      7      8
i      2      3      5      2      1
j      9      3      7      6      5

In [10]:
# 컬럼 기준으로 인덱싱 
# sample_df['var_1'] : series 형태로 반환함
sample_df[['var_1']]

var_1
a      2
b      4
c      5
d      1
e      4
f      5
g      7
h      8
i      2
j      9

In [12]:
sample_df.loc[['a']]

var_1  var_2  var_3  var_4  var_5
a      2      2      1      4      3

In [13]:
sample_df.loc[['a', 'b', 'c']]

var_1  var_2  var_3  var_4  var_5
a      2      2      1      4      3
b      4      3      3      7      1
c      5      4      6      3      5

In [16]:
sample_df.loc['a': 'c']

var_1  var_2  var_3  var_4  var_5
a      2      2      1      4      3
b      4      3      3      7      1
c      5      4      6      3      5

In [19]:
sample_df.iloc[0:3]

var_1  var_2  var_3  var_4  var_5
a      2      2      1      4      3
b      4      3      3      7      1
c      5      4      6      3      5

In [21]:
sample_df.iloc[0:3, 2:4] #행, 열

var_3  var_4
a      1      4
b      3      7
c      6      3

In [23]:
sample_df.drop('var_1', axis = 1) # axis = 1: 컬럼을 삭제함

var_2  var_3  var_4  var_5
a      2      1      4      3
b      3      3      7      1
c      4      6      3      5
d      4      5      6      7
e      5      7      8      3
f      4      8      9      4
g      5      2      0      6
h      8      1      7      8
i      3      5      2      1
j      3      7      6      5

In [24]:
sample_df.drop(['var_1', 'var_2'], axis = 1)

var_3  var_4  var_5
a      1      4      3
b      3      7      1
c      6      3      5
d      5      6      7
e      7      8      3
f      8      9      4
g      2      0      6
h      1      7      8
i      5      2      1
j      7      6      5

In [25]:
sample_df.drop(['a', 'b', 'c'])

var_1  var_2  var_3  var_4  var_5
d      1      4      5      6      7
e      4      5      7      8      3
f      5      4      8      9      4
g      7      5      2      0      6
h      8      8      1      7      8
i      2      3      5      2      1
j      9      3      7      6      5

In [33]:
# 인덱스를 추가함
sample_df = sample_df.reset_index()

In [28]:
# 기존 인덱스를 제거하고 인덱스를 추가함
sample_df.reset_index(drop=True)

var_1  var_2  var_3  var_4  var_5
0      2      2      1      4      3
1      4      3      3      7      1
2      5      4      6      3      5
3      1      4      5      6      7
4      4      5      7      8      3
5      5      4      8      9      4
6      7      5      2      0      6
7      8      8      1      7      8
8      2      3      5      2      1
9      9      3      7      6      5

In [35]:
# var_1 을 인덱스로 지정함
sample_df = sample_df.set_index('var_1')
sample_df.columns

Index(['var_2', 'var_3', 'var_4', 'var_5'], dtype='object')

In [37]:
sample_df.sum()

var_1    47
var_2    41
var_3    45
var_4    52
var_5    43
dtype: int64

In [39]:
sample_df.agg(['sum', 'mean']) # .aggregate도 가능함

var_1  var_2  var_3  var_4  var_5
sum    47.0   41.0   45.0   52.0   43.0
mean    4.7    4.1    4.5    5.2    4.3

In [42]:
file_url = 'https://media.githubusercontent.com/media/musthave-ML10/data_source/main/iris.csv';

iris = pd.read_csv(file_url)
iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  6.1               3.0                4.6               1.4   
1                  7.2               3.0                5.8               1.6   
2                  6.7               3.1                4.4               1.4   
3                  6.2               2.9                4.3               1.3   
4                  4.6               3.4                1.4               0.3   
..                 ...               ...                ...               ...   
145                5.7               2.5                5.0               2.0   
146                6.3               2.9                5.6               1.8   
147                6.8               3.2                5.9               2.3   
148                6.1               2.8                4.7               1.2   
149                5.1               2.5                3.0               1.1   

          class  
0    versicolor  
1     virginica  
2    versicolor  
3    versicolor  
4        setosa  
..          ...  
145   virginica  
146   virginica  
147   virginica  
148  versicolor  
149  versicolor  

[150 rows x 5 columns]

In [43]:
iris.groupby('class').mean()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
class                                                                
setosa                  5.006             3.428              1.462   
versicolor              5.936             2.770              4.260   
virginica               6.588             2.974              5.552   

            petal width (cm)  
class                         
setosa                 0.246  
versicolor             1.326  
virginica              2.026

In [44]:
iris.groupby('class').agg(['count', 'mean'])

sepal length (cm)        sepal width (cm)        petal length (cm)  \
                       count   mean            count   mean             count   
class                                                                           
setosa                    50  5.006               50  3.428                50   
versicolor                50  5.936               50  2.770                50   
virginica                 50  6.588               50  2.974                50   

                  petal width (cm)         
             mean            count   mean  
class                                      
setosa      1.462               50  0.246  
versicolor  4.260               50  1.326  
virginica   5.552               50  2.026

In [45]:
iris['class'].unique()

array(['versicolor', 'virginica', 'setosa'], dtype=object)

In [46]:
iris['class'].nunique()

3

In [47]:
iris['class'].value_counts()

versicolor    50
virginica     50
setosa        50
Name: class, dtype: int64

In [48]:
left_url = 'https://media.githubusercontent.com/media/musthave-ML10/data_source/main/left.csv';
right_url = 'https://media.githubusercontent.com/media/musthave-ML10/data_source/main/right.csv';

left = pd.read_csv(left_url)
right = pd.read_csv(right_url)

In [50]:
left

key  var_1  var_2
0   a      1      1
1   b      3      2
2   c      4      4
3   d      2      3
4   e      1      0

In [52]:
right

key  var_3  var_4
0   b      4      3
1   c      6      5
2   e      3      8
3   f      2      7
4   g      3      4

In [53]:
left.merge(right)

key  var_1  var_2  var_3  var_4
0   b      3      2      4      3
1   c      4      4      6      5
2   e      1      0      3      8

In [54]:
left.merge(right, how ='left') #on=어떤 컬럼으로 머지할지

key  var_1  var_2  var_3  var_4
0   a      1      1    NaN    NaN
1   b      3      2    4.0    3.0
2   c      4      4    6.0    5.0
3   d      2      3    NaN    NaN
4   e      1      0    3.0    8.0

In [55]:
left.merge(right, how ='right')

key  var_1  var_2  var_3  var_4
0   b    3.0    2.0      4      3
1   c    4.0    4.0      6      5
2   e    1.0    0.0      3      8
3   f    NaN    NaN      2      7
4   g    NaN    NaN      3      4

In [56]:
left.merge(right, how='outer')

key  var_1  var_2  var_3  var_4
0   a    1.0    1.0    NaN    NaN
1   b    3.0    2.0    4.0    3.0
2   c    4.0    4.0    6.0    5.0
3   d    2.0    3.0    NaN    NaN
4   e    1.0    0.0    3.0    8.0
5   f    NaN    NaN    2.0    7.0
6   g    NaN    NaN    3.0    4.0

In [59]:
#.join() 인덱스를 Key로 삼아서 테이블을 결합
#left.join(right) # key라는 컬럼이 겹쳐서 오류 발생함

In [60]:
left.drop('key', axis=1).join(right.drop('key', axis=1))

var_1  var_2  var_3  var_4
0      1      1      4      3
1      3      2      6      5
2      4      4      3      8
3      2      3      2      7
4      1      0      3      4

In [61]:
# key 컬럼 기준으로 합치기 
left = left.set_index('key')
right = right.set_index('key')
left.join(right)

var_1  var_2  var_3  var_4
key                            
a        1      1    NaN    NaN
b        3      2    4.0    3.0
c        4      4    6.0    5.0
d        2      3    NaN    NaN
e        1      0    3.0    8.0

In [62]:
left.join(right, how = 'left')

var_1  var_2  var_3  var_4
key                            
a        1      1    NaN    NaN
b        3      2    4.0    3.0
c        4      4    6.0    5.0
d        2      3    NaN    NaN
e        1      0    3.0    8.0

In [63]:
left

var_1  var_2
key              
a        1      1
b        3      2
c        4      4
d        2      3
e        1      0

In [64]:
right

var_3  var_4
key              
b        4      3
c        6      5
e        3      8
f        2      7
g        3      4

In [66]:
# 행 기준으로 결합
pd.concat([left, right])

var_1  var_2  var_3  var_4
key                            
a      1.0    1.0    NaN    NaN
b      3.0    2.0    NaN    NaN
c      4.0    4.0    NaN    NaN
d      2.0    3.0    NaN    NaN
e      1.0    0.0    NaN    NaN
b      NaN    NaN    4.0    3.0
c      NaN    NaN    6.0    5.0
e      NaN    NaN    3.0    8.0
f      NaN    NaN    2.0    7.0
g      NaN    NaN    3.0    4.0

In [67]:
# 열기준으로 결합
pd.concat([left, right], axis= 1)

var_1  var_2  var_3  var_4
key                            
a      1.0    1.0    NaN    NaN
b      3.0    2.0    4.0    3.0
c      4.0    4.0    6.0    5.0
d      2.0    3.0    NaN    NaN
e      1.0    0.0    3.0    8.0
f      NaN    NaN    2.0    7.0
g      NaN    NaN    3.0    4.0

In [68]:
import numpy as np

In [69]:
np.array([1, 2, 3])

array([1, 2, 3])

In [70]:
np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [74]:
np.array(sample_df)

array([[2, 2, 1, 4, 3],
       [4, 3, 3, 7, 1],
       [5, 4, 6, 3, 5],
       [1, 4, 5, 6, 7],
       [4, 5, 7, 8, 3],
       [5, 4, 8, 9, 4],
       [7, 5, 2, 0, 6],
       [8, 8, 1, 7, 8],
       [2, 3, 5, 2, 1],
       [9, 3, 7, 6, 5]])

In [76]:
sample_np = np.array(sample_df)
pd.DataFrame(sample_np)

0  1  2  3  4
0  2  2  1  4  3
1  4  3  3  7  1
2  5  4  6  3  5
3  1  4  5  6  7
4  4  5  7  8  3
5  5  4  8  9  4
6  7  5  2  0  6
7  8  8  1  7  8
8  2  3  5  2  1
9  9  3  7  6  5

In [79]:
pd.DataFrame(sample_np, columns=sample_df.columns) # sample_np를 dataframe으로 만드는데 컬럼명은 sample_df.columns를 가져와

var_1  var_2  var_3  var_4  var_5
0      2      2      1      4      3
1      4      3      3      7      1
2      5      4      6      3      5
3      1      4      5      6      7
4      4      5      7      8      3
5      5      4      8      9      4
6      7      5      2      0      6
7      8      8      1      7      8
8      2      3      5      2      1
9      9      3      7      6      5

In [81]:
sample_np

array([[2, 2, 1, 4, 3],
       [4, 3, 3, 7, 1],
       [5, 4, 6, 3, 5],
       [1, 4, 5, 6, 7],
       [4, 5, 7, 8, 3],
       [5, 4, 8, 9, 4],
       [7, 5, 2, 0, 6],
       [8, 8, 1, 7, 8],
       [2, 3, 5, 2, 1],
       [9, 3, 7, 6, 5]])

In [80]:
sample_np[0] # 첫번째 행을 가져와

array([2, 2, 1, 4, 3])

In [83]:
sample_np[0, 3] # (0, 3) 가져와

4

In [85]:
sample_np[0:2, 1:2] # 0:2 > 행을 인덱싱 1:2 > 열을 인덱싱

array([[2],
       [3]])

In [87]:
sample_np[:, 2] #행은 전체 다, 열은 3번째만

array([1, 3, 6, 5, 7, 8, 2, 1, 5, 7])

In [89]:
np_a = np.array([[1, 3], [0, -2]])
np_a

array([[ 1,  3],
       [ 0, -2]])

In [92]:
np_a + 10 # 사칙연산 모두 가능

array([[11, 13],
       [10,  8]])

In [94]:
np_b = np.array([[1, 0], [0, 1]])
np_b

array([[1, 0],
       [0, 1]])

In [96]:
np_a + np_b # np끼리 연산 가능

array([[ 2,  3],
       [ 0, -1]])

In [97]:
np_a * np_b 

array([[ 1,  0],
       [ 0, -2]])

In [98]:
np_a @ np_b # 행렬의 곱셈은 요렇게

array([[ 1,  3],
       [ 0, -2]])

In [99]:
np.random.randint(11) # 0-10까지 임의의 숫자 불러옴

10

In [100]:
np.random.randint(50, 71) # 50-70까지 임의의 숫자 불러옴 

67

In [101]:
np.random.randint(50, 71, 5) # 50-70까지 5개를 랜덤하게 불러옴

array([50, 52, 66, 52, 61])

In [103]:
np.random.choice(['red', 'green', 'white', 'black', 'blue'], size = 3) # 배열중 3개를 랜덤하게 불러옴

array(['black', 'black', 'red'], dtype='<U5')

In [104]:
np.random.choice(['red', 'green', 'white', 'black', 'blue'], size = 3, replace=False) # 배열중 3개를 랜덤하게 불러오는데 중복은 허용안함

array(['blue', 'green', 'white'], dtype='<U5')

In [105]:
np.arange(1, 11) # 1 ~ 10까지

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
np.arange(1, 11, 2) # 1 ~ 10까지 2씩 건너띄면서

array([1, 3, 5, 7, 9])

In [111]:
np.linspace(1, 10, 4) # 1-10까지 4개를 가져오는데 균등하게 띄어서

array([ 1.,  4.,  7., 10.])